FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:stretch-run-20190612

RUN apt-get update && \
  apt-get install -y --no-install-recommends omxplayer fbset python3-dbus && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

ENV DBUS_SYSTEM_BUS_ADDRESS unix:path=/host/run/dbus/system_bus_socket

WORKDIR /usr/src/app
COPY avahi avahi
COPY start.py ./

CMD ["python3", "/usr/src/app/start.py"]
