FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:stretch-run

RUN apt-get update && \
  apt-get install -y --no-install-recommends omxplayer fbset && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app
COPY ./start.sh /usr/src/app/start.sh

CMD ["/usr/src/app/start.sh"]
