FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:stretch-run

RUN apt-get update && \
  apt-get install python3-dbus && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

ENV DBUS_SYSTEM_BUS_ADDRESS unix:path=/host/run/dbus/system_bus_socket

WORKDIR /usr/src/app

COPY avahi avahi
COPY announce.py ./

CMD ["python3", "announce.py"]
